### ISSUE TITLE
ERROR: VINS-Mono initialization is poor

### ISSUE THREAD

**Issue by unravelwool** [uzh-rpg/deep_drone_acrobatics#3]
hello! 
When I was running "_Let's do a Power Loop_", there is an error arising:
`[ERROR] [1600958393.127985, 30.683000]: VINS-Mono initialization is poor, keeping ground truth estimate!`
This error also arised when running "_Train your own acrobatic controller_". 

 I read the code and have found this:
```
self.vins_mono_sub = rospy.Subscriber("/vins_estimator/imu_propagate", Odometry,self.callback_vins_mono, queue_size=1)
def callback_vins_mono(self, data):
self.vins_odometry = data
......
def vio_init_good(self):
max_allowed_velocity = 0.1
if abs(self.vins_odometry.twist.twist.linear.x) < max_allowed_velocity and \
abs(self.vins_odometry.twist.twist.linear.y) < max_allowed_velocity and \
abs(self.vins_odometry.twist.twist.linear.z) < max_allowed_velocity:
return True
else:
return False
......
vio_init_good = learner.vio_init_good
if vio_init_good:
rospy.loginfo("VINS-Mono initialization is good, switching to vision-based state estimate!")
os.system("timeout 1s rostopic pub /switch_odometry std_msgs/Int8 'data: 1'")
else:
if use_chimaera:
rospy.logerr("VINS-Mono initialization is poor, use orientation, bodyrates from VIO and linear velocity estimate from GT!")
os.system("timeout 1s rostopic pub /switch_odometry std_msgs/Int8 'data: 2'")
else:
rospy.logerr("VINS-Mono initialization is poor, keeping ground truth estimate!")
os.system("timeout 1s rostopic pub /switch_odometry std_msgs/Int8 'data: 0'")
```
The meaning of this code is that the node received messages from "/vins_estimator/imu_propagate" topic, and see whether the linear velocity of x/y/z axis is less than "_max_allowed_velocity_". And according to the judgment, the process chooses the source of the state information of the uav.

This error maybe illustrates that the messages from "/vins_estimator/imu_propagate" topic are incorrect, and I have observed the  
messages from this topic:
```
header:
  seq: 27182
  stamp:
    secs: 30
    nsecs: 676000000
  frame_id: "world"
child_frame_id: ''
pose:
  pose:
    position:
      x: 348.302958341977
      y: -92.38841451362987
      z: 455.0951824682847
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 0.0
  covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
twist:
  twist:
    linear:
      x: 13.164381097756815
      y: -6.618070445507301
      z: 95.78546687709526
    angular:
      x: -0.028017004185567372
      y: 0.004907724878181774
      z: 0.0004419178697962628
  covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
-----------------------------------------
header:
  seq: 59321
  stamp:
    secs: 67
    nsecs: 653000000
  frame_id: "world"
child_frame_id: ''
pose:
  pose:
    position:
      x: -33.61205200835233
      y: 40.2259080436137
      z: 990.275283782915
    orientation:
      x: -0.04461572714552553
      y: -0.002277912941237847
      z: 0.014164844224923045
      w: 0.9989026089379811
  covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
twist:
  twist:
    linear:
      x: -3.424379467601957
      y: 3.7944451802777066
      z: 141.73200192600186
    angular:
      x: -0.016607839462576133
      y: 0.009083643241368674
      z: 0.010069951975026947
  covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
-----------------------------------------
header:
  seq: 86061
  stamp:
    secs: 98
    nsecs: 463000000
  frame_id: "world"
child_frame_id: ''
pose:
  pose:
    position:
      x: -2.4236050470843185
      y: -0.8900145764604871
      z: 4.197753049114425
    orientation:
      x: 0.0023747880847325774
      y: 0.00023300498559695584
      z: 0.22972326994687156
      w: 0.9732530673801754
  covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
twist:
  twist:
    linear:
      x: -0.13332384220557
      y: 0.0026161341345475207
      z: 0.11045725267295822
    angular:
      x: -0.001508592949039637
      y: -0.0020991892371375245
      z: 0.015469017113575614
  covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
-----------------------------------------
header:
  seq: 115882
  stamp:
    secs: 132
    nsecs: 533000000
  frame_id: "world"
child_frame_id: ''
pose:
  pose:
    position:
      x: 0.09508827283386542
      y: 0.7051479254568498
      z: 0.365840766024347
    orientation:
      x: -0.04117269056392
      y: 0.0029551340953488017
      z: 0.0027033346370284117
      w: 0.9991440199536085
  covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
twist:
  twist:
    linear:
      x: -0.05540701501453761
      y: -0.07778408086123147
      z: -0.0941141972114571
    angular:
      x: -0.029499468272388422
      y: 0.015262373913439648
      z: 0.007893456185489445
  covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
-----------------------------------------
header:
  seq: 142764
  stamp:
    secs: 163
    nsecs: 739000000
  frame_id: "world"
child_frame_id: ''
pose:
  pose:
    position:
      x: -105.82663903706502
      y: 298.04912190536623
      z: -90.30937762830236
    orientation:
      x: -0.15176203822609244
      y: -0.011775980944180494
      z: 0.2348159682707444
      w: 0.9600961300480978
  covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
twist:
  twist:
    linear:
      x: -12.479729600473537
      y: 29.75990696262599
      z: -5.247747170775202
    angular:
      x: -0.03523135578896464
      y: -0.004625335332755807
      z: -0.0030960837436363863
  covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
-----------------------------------------
```
These five messages are ones that the subscriber received and used to determine "vio_init_good" in the five experiments of "_Let's do a Power Loop_". Of the five messages, only one meets the requirements and the node switchs to "vision-based state estimate", others make the node set to "ground truth estimate".

I think the code about vins_estimator is maybe not robust and has some bug. Can you tell me how to fix this error? I would be grateful if you could help me :)
